##############################################################################
##			Senal's Helix Config
##
##
##############################################################################




###########################################
##		Theme			  #
##					  #
###########################################


theme = "onedark"



###########################################
##		Spaces 			  #
##					  #
###########################################

[editor.whitespace.render]
space = "8"
tab = "8"
newline = "none"
